import z, { array, boolean, date, number, object, string, TypeOf } from "zod";

export const DatabaseZod = object({
  version: number(),
  cameras: array(
    object({
      id: string(),
      name: string(),
      notes: string(),
      address: string(),
      recording: number(),
      config: object({
        stream: z.enum(["Off", "Low Latency", "High Quality", "AI Tracking"]),
        focus: z.enum(["Auto Focus", "Manual Focus"]),
        whiteBalance: z.enum([
          "Auto",
          "Indoor",
          "Outdoor",
          "One Push",
          "Manual",
        ]),
        exposure: z.enum([
          "Auto",
          "Manual",
          "Shutter Priority",
          "Iris Priority",
          "Brightness Priority",
        ]),
        shutterSpeed: z.enum([
          "1/30",
          "1/60",
          "1/90",
          "1/100",
          "1/125",
          "1/180",
          "1/250",
          "1/350",
          "1/500",
          "1/725",
          "1/1000",
          "1/1500",
          "1/2000",
          "1/3000",
          "1/4000",
          "1/6000",
          "1/10000",
        ]),
        iris: z.enum([
          "Closed",
          "f/11",
          "f/9.6",
          "f/8",
          "f/6.8",
          "f/5.6",
          "f/4.8",
          "f/4.0",
          "f/3.4",
          "f/2.8",
          "f/2.4",
          "f/2.0",
          "f/1.8",
        ]),
        brightness: z.enum([
          "0",
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
        ]),
        afSensitivity: z.enum(["High", "Normal", "Low"]),
        orientation: z.enum([
          "Typical",
          "Mirrored",
          "Flipped",
          "Mirrored + Flipped",
        ]),
        saturation: z.enum([
          "60%",
          "70%",
          "80%",
          "90%",
          "100%",
          "110%",
          "120%",
          "130%",
          "140%",
          "150%",
          "160%",
          "170%",
          "180%",
          "190%",
          "200%",
        ]),
      }),
    })
  ),
  settings: object({
    darkMode: boolean(),
    control: object({
      requireFocus: boolean(),
      keyboardMode: z.enum(["left", "right", "arrow"]),
      gamepadMode: z.enum(["left", "right", "split", "trigger"]),
    }),
    speed: object({
      mode: z.enum([
        "constant",
        "linear",
        "square",
        "squareRoot",
        "exponentialIn",
        "exponentialOut",
        "trig",
      ]),
      pan: number(),
      tilt: number(),
      zoom: number(),
      focus: number(),
      preset: number(),
    }),
  }),
});
export type DatabaseType = TypeOf<typeof DatabaseZod>;
export const DatabaseConfigZod = DatabaseZod.shape.cameras.element.shape.config;
export type DatabaseConfigType = TypeOf<typeof DatabaseConfigZod>;
